# Generated by Django 5.1.1 on 2024-10-01 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general_ledger", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalinvoice",
            name="invoice_number",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="purchaseinvoice",
            name="invoice_number",
            field=models.CharField(max_length=20),
        ),
    ]
