# Generated by Django 5.1.1 on 2024-10-02 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("general_ledger", "0003_bankstatementline_ofx_fitid_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bankstatementline",
            options={
                "ordering": ["date", "index", "name"],
                "verbose_name": "Bank Statement Line",
                "verbose_name_plural": "Bank Statement Lines",
            },
        ),
    ]
