# Generated by Django 5.1.1 on 2024-10-02 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general_ledger", "0004_alter_bankstatementline_options"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="bankstatementline",
            constraint=models.UniqueConstraint(
                fields=("bank", "date", "index"),
                name="bankstatementline_uniq_bank_date_index",
            ),
        ),
    ]
