# Generated by Django 5.1.1 on 2024-10-02 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "general_ledger",
            "0005_bankstatementline_bankstatementline_uniq_bank_date_index",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bankstatementline",
            options={
                "ordering": ["date", "index"],
                "verbose_name": "Bank Statement Line",
                "verbose_name_plural": "Bank Statement Lines",
            },
        ),
    ]
