# Generated by Django 5.1.1 on 2024-10-02 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general_ledger", "0006_alter_bankstatementline_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankbalance",
            name="balance_type",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
