# Generated by Django 5.1.1 on 2024-10-04 04:55

import django.db.models.deletion
import simple_history.models
import uuid
import xstate_machine
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general_ledger", "0001_squashed_0007_bankbalance_balance_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bankbalance",
            options={
                "ordering": ["balance_date"],
                "verbose_name": "Bank Balance",
                "verbose_name_plural": "Bank Balances",
            },
        ),
        migrations.CreateModel(
            name="HistoricalPayment",
            fields=[
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4)),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("date", models.DateField()),
                (
                    "amount",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=16),
                ),
                ("is_posted", models.BooleanField(default=False)),
                ("is_paid", models.BooleanField(default=False)),
                ("is_locked", models.BooleanField(default=False)),
                ("is_system", models.BooleanField(default=False)),
                (
                    "state",
                    xstate_machine.FSMField(
                        choices=[
                            ("DR", "Draft"),
                            ("RE", "Recorded"),
                            ("PO", "Posted"),
                            ("PA", "Partial"),
                            ("CO", "Complete"),
                            ("CA", "Cancelled"),
                            ("VO", "Void"),
                        ],
                        default="DR",
                        max_length=50,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ledger",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="general_ledger.ledger",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Payment",
                "verbose_name_plural": "historical Payments",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
