# Generated by Django 5.1.1 on 2024-10-04 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general_ledger", "0008_alter_bankbalance_options_historicalpayment"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileupload",
            name="book",
            field=models.ForeignKey(
                default="fd1bb212-4163-4dea-b3eb-fb2539d9d16c",
                on_delete=django.db.models.deletion.CASCADE,
                to="general_ledger.book",
            ),
            preserve_default=False,
        ),
    ]
