# Generated by Django 5.1.1 on 2024-10-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general_ledger", "0010_alter_bank_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bank",
            name="close_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bank",
            name="open_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
