# Generated by Django 5.1.1 on 2024-10-04 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("general_ledger", "0011_bank_close_date_bank_open_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bank",
            name="routing_number",
        ),
    ]
