# Generated by Django 5.1.1 on 2024-10-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general_ledger", "0012_remove_bank_routing_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="bank",
            name="routing_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
