# Generated by Django 5.1.1 on 2024-10-04 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general_ledger", "0013_bank_routing_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="bank",
            name="closing_balance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="general_ledger.bankbalance",
            ),
        ),
        migrations.AddField(
            model_name="bank",
            name="opening_balance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="general_ledger.bankbalance",
            ),
        ),
    ]
