# Generated by Django 5.1.1 on 2024-10-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general_ledger", "0015_bankbalance_bankbalance_uniq_bank_date_balance_type"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="bankbalance",
            name="bankbalance_uniq_bank_date_balance_type",
        ),
        migrations.AddConstraint(
            model_name="bankbalance",
            constraint=models.UniqueConstraint(
                fields=("bank", "balance_date", "balance_type"),
                name="bankbalance_uniq_bank_date_balance_type",
            ),
        ),
    ]
