# Generated by Django 5.1.1 on 2024-10-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "general_ledger",
            "0015_bankbalance_bankbalance_uniq_bank_date_balance_type_squashed_0016_remove_bankbalance_bankbalance_uniq_bank_date_balance_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankstatementline",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
