# Generated by Django 5.1.1 on 2024-10-04 22:55

import timezone_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("general_ledger", "0018_bankstatementline_ofx_dtposted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankstatementline",
            name="tz",
            field=timezone_field.fields.TimeZoneField(default="Europe/London"),
        ),
    ]
