# Generated by Django 5.1.1 on 2024-10-05 11:43

import timezone_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("general_ledger", "0019_bankstatementline_tz"),
    ]

    operations = [
        migrations.AddField(
            model_name="bank",
            name="tz",
            field=timezone_field.fields.TimeZoneField(default="Europe/London"),
        ),
    ]
