# Generated by Django 5.1.1 on 2024-10-05 12:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general_ledger", "0020_bank_tz"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankstatementline",
            name="datetime",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bankstatementline",
            name="date",
            field=models.DateField(),
        ),
    ]
