# Generated by Django 5.1.1 on 2024-10-05 14:37

import timezone_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("general_ledger", "0021_bankstatementline_datetime_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankbalance",
            name="balance_date_tz",
            field=timezone_field.fields.TimeZoneField(default="Europe/London"),
        ),
    ]
