# Generated by Django 5.1.1 on 2024-10-05 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("general_ledger", "0022_bankbalance_balance_date_tz"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fileupload",
            options={
                "ordering": ["-uploaded_at"],
                "verbose_name": "Uploaded file",
                "verbose_name_plural": "Uploaded files",
            },
        ),
        migrations.AlterModelTable(
            name="fileupload",
            table="gl_file_upload",
        ),
    ]
