# Generated by Django 5.1.1 on 2024-10-10 10:18

import general_ledger.models.file_upload
import general_ledger.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general_ledger", "0023_alter_fileupload_options_alter_fileupload_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accounttype",
            name="category",
            field=models.CharField(
                choices=[
                    ("A", "Asset"),
                    ("L", "Liability"),
                    ("E", "Equity"),
                    ("R", "Revenue"),
                    ("X", "Expense"),
                    ("NCA", "Non-Current Asset"),
                    ("CA", "Current Asset"),
                    ("NCL", "Non-Current Liability"),
                    ("CL", "Current Liability"),
                ],
                default="A",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="fileupload",
            name="file",
            field=models.FileField(
                upload_to=general_ledger.models.file_upload.generate_unique_filename,
                validators=[general_ledger.validators.validate_file_size],
            ),
        ),
    ]
