# Generated by Django 5.1.1 on 2024-10-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general_ledger", "0024_alter_accounttype_category_alter_fileupload_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accounttype",
            name="category",
            field=models.CharField(
                choices=[
                    ("E", "Equity"),
                    ("R", "Revenue"),
                    ("X", "Expense"),
                    ("NCA", "Non-Current Asset"),
                    ("CA", "Current Asset"),
                    ("NCL", "Non-Current Liability"),
                    ("CL", "Current Liability"),
                ],
                max_length=20,
            ),
        ),
    ]
