# Generated by Django 5.1.1 on 2024-10-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general_ledger", "0025_alter_accounttype_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="accounttype",
            name="liquidity",
            field=models.IntegerField(
                choices=[
                    (100, "Cash or Cash Equivalent"),
                    (90, "Bank"),
                    (80, "Accounts Receivable"),
                    (75, "Accounts Payable"),
                    (70, "Inventory"),
                    (65, "Loans Due within 12 months"),
                    (60, "Other Current Assets"),
                    (50, "Motor Vehicles"),
                    (40, "Machinery and Equipment"),
                    (30, "Fixtures and Fittings"),
                    (20, "Land and Buildings"),
                ],
                default=50,
            ),
            preserve_default=False,
        ),
    ]
