# Generated by Django 5.1.1 on 2024-10-10 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("general_ledger", "0027_alter_accounttype_liquidity"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={
                "ordering": ["type__category", "type__liquidity", "name"],
                "verbose_name_plural": "accounts",
            },
        ),
        migrations.AlterModelOptions(
            name="accounttype",
            options={
                "ordering": ["category", "liquidity", "name"],
                "verbose_name": "Account Type",
                "verbose_name_plural": "Account Types",
            },
        ),
    ]
