# Generated by Django 5.1.1 on 2024-10-26 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dashboard", "0001_initial"),
        ("general_ledger", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookpreferencemodel",
            name="instance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="general_ledger.book"
            ),
        ),
    ]
